#!/usr/bin/env bash

# set wheel group to no-password for sudo actions
echo "%wheel         ALL = (ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers

# set path for makepkg package saving in one folder
echo PKGDEST=/home/build/packages >> /etc/makepkg.conf

# install yay and git
pacman -Sy --noconfirm --needed git yay

# create user
useradd -m -G wheel -s /bin/bash build

mkdir /home/build/packages
chown -R build:build /home/build/packages

sudo -u build yay -S --noconfirm cava
sudo -u build yay -S --noconfirm nwg-look-bin
sudo -u build yay -S --noconfirm wlogout
sudo -u build yay -S --noconfirm swww
sudo -u build yay -S --noconfirm networkmanager-dmenu-bluetoothfix-git
sudo cp /home/build/packages/* EndeavourOS-Community-hyprland-ISO/airootfs/root/packages/

# Build liveuser skel
sudo chown -R build:build EndeavourOS-Community-hyprland-ISO/airootfs/root/endeavouros-skel-liveuser
cd EndeavourOS-Community-hyprland-ISO/airootfs/root/endeavouros-skel-liveuser
sudo -u build makepkg -f
