#!/usr/bin/env bash

# set wheel group to no-password for sudo actions
echo "%wheel         ALL = (ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers

# set path for makepkg package saving in one folder
cp -a /etc/makepkg.conf /etc/makepkg.conf.bak
echo PKGDEST=/home/build/packages >> /etc/makepkg.conf

# create user
useradd -m -G wheel -s /bin/bash build

mkdir /home/build/packages
chown -R build:build /home/build/packages

sudo -u build yay -S --noconfirm cava
sudo -u build yay -S --noconfirm nwg-look-bin
sudo -u build yay -S --noconfirm wlogout
sudo -u build yay -S --noconfirm swww
sudo -u build yay -S --noconfirm networkmanager-dmenu-bluetoothfix-git
sudo cp /home/build/packages/* EndeavourOS-Community-hyprland-ISO/airootfs/root/packages/
sudo pacman -Rsc --noconfirm cava nwg-look-bin wlogout swww networkmanager-dmenu-bluetoothfix-git

# Build liveuser skel
sudo cp -a /etc/makepkg.conf.bak /etc/makepkg.conf
sudo chown -R build:build EndeavourOS-Community-hyprland-ISO/airootfs/root/endeavouros-skel-liveuser
cd EndeavourOS-Community-hyprland-ISO/airootfs/root/endeavouros-skel-liveuser
sudo -u build makepkg -f
exit
userdel -f build
